export const arrayOfItems = [
    {
        id: 88377,
        title: 'Stolen 2018 VAUN VELO(black)',
        description: 'Stolen from my courtyard',
        address: 'Berlin, 12047, DE',
        occurredAt: 1532152800,
        updatedAt: 1557813447,
        url: 'https://bikewise.org/api/v1/incidents/88377',
        source: {
            name: 'BikeIndex.org',
            htmlUrl: 'https://bikeindex.org/bikes/403765',
            apiUrl: 'https://bikeindex.org/api/v1/bikes/403765',
        },
        media: {
            imageUrl: null,
            imageUrlThumb: null,
        },
        locationType: null,
        locationDescription: null,
        type: 'Theft',
        typeProperties: null,
    },
    {
        id: 92457,
        title: 'Stolen ROCKRIDER black-grey(black and blue)',
        description: null,
        address: 'Berlin, 10999, DE',
        occurredAt: 1538931327,
        updatedAt: 1557813728,
        url: 'https://bikewise.org/api/v1/incidents/92457',
        source: {
            name: 'BikeIndex.org',
            htmlUrl: 'https://bikeindex.org/bikes/439032',
            apiUrl: 'https://bikeindex.org/api/v1/bikes/439032',
        },
        media: {
            imageUrl: null,
            imageUrlThumb: null,
        },
        locationType: null,
        locationDescription: null,
        type: 'Theft',
        typeProperties: null,
    },
];

export const indexedObject = {
    '88377': {
        id: 88377,
        title: 'Stolen 2018 VAUN VELO(black)',
        description: 'Stolen from my courtyard',
        address: 'Berlin, 12047, DE',
        occurredAt: 1532152800,
        updatedAt: 1557813447,
        url: 'https://bikewise.org/api/v1/incidents/88377',
        source: {
            name: 'BikeIndex.org',
            htmlUrl: 'https://bikeindex.org/bikes/403765',
            apiUrl: 'https://bikeindex.org/api/v1/bikes/403765',
        },
        media: {
            imageUrl: null,
            imageUrlThumb: null,
        },
        locationType: null,
        locationDescription: null,
        type: 'Theft',
        typeProperties: null,
    },
    '92457': {
        id: 92457,
        title: 'Stolen ROCKRIDER black-grey(black and blue)',
        description: null,
        address: 'Berlin, 10999, DE',
        occurredAt: 1538931327,
        updatedAt: 1557813728,
        url: 'https://bikewise.org/api/v1/incidents/92457',
        source: {
            name: 'BikeIndex.org',
            htmlUrl: 'https://bikeindex.org/bikes/439032',
            apiUrl: 'https://bikeindex.org/api/v1/bikes/439032',
        },
        media: {
            imageUrl: null,
            imageUrlThumb: null,
        },
        locationType: null,
        locationDescription: null,
        type: 'Theft',
        typeProperties: null,
    },
};
